### PR TITLE
Fix problem with seeds

### PR DESCRIPTION
**Pull request by noxify**
As explained in #58, here the fix to enable the seeds for postgres, mysql and sqlite.

### CODE REVIEW

**Comment by Omranic** [comment]
Well, even if this is valid but I kinda find it overwhelming solution! Is there any other simpler database cross-platform solution for this issues, personally I didn't hit that case before to be honest ..

**Comment by noxify** [comment]
Hi,

with mysql everything works fine.

But since I changed the database, i have the problem with the seeds.

We can close this PR and keep this as "known issue" with an issue.

**Comment by Omranic** [comment]
Well, keep it open for now. I'll get back to it later, as I can see initially it's something that affects any Laravel seeds, and that's a good opportunity for submitting a PR to the core or at least developing a new package for it..

**Comment by noxify** [comment]
Ok. Thanks!

**Comment by Omranic** [comment]
Seems to be out of focus for the current and next quarter honestly, so will be closed for now. Seeds and migrations could be published and customized easily if needed as a way around anyway 🙂

**Pull request closed without merging**
