### PR TITLE
changed frontend common layout to extend an example layout template t…

### PR DESCRIPTION
**Pull request by emahuni**
…hat uses cdn scripts, styles and fonts.

- added explanation at the bottom of the example layout template.

### CODE REVIEW

**Comment by Omranic** [comment]
Thanks for the nice PR
Just a quick note, we've now two separate layouts for both ends: Frontend/Backend so I've added the missing one & fixed some paths in this commit 61f5e4aba1153421640c14872e2877d0939c9cda

**Comment by emahuni** [comment]
I didn't do the same for backend because of the 'user' SQL error, I'm yet to look into it.

**Comment by emahuni** [comment]
Oh ok. I had just written that comment and was yet to post it :D

**Comment by Omranic** [comment]
Backend dashboard SQL error fixed in 9fc2c5f

**Pull request merged**
